### ISSUE TITLE
Move to YAML-based builds

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.eventgrid.proxy#35]
Move to YAML based builds which are stored in the GitHub repo under `build` folder.

- [X] Migrate CI Build
- [x] Migrate release to Docker Hub
- [x] Update CI badge in README

**Comment by tomkerkhove** [comment]
Let's stick with MyGet for now @stijnmoreels, see https://github.com/arcus-azure/arcus/issues/29

**Comment by stijnmoreels** [comment]
The current release definition of the Docker Hub contains a variable that doesn't seemed to be specified somewhere: `$(Image.MajorMinorVersion)`.
What value should this variable have? And should it be configurable at queue-time?

**Comment by tomkerkhove** [comment]
It's defined as part of the `Determine '{major}.{minor}' version` step

**Comment by tomkerkhove** [comment]
While we are changing that build we should use Docker v2 Task

**Comment by stijnmoreels** [comment]
Tried this already but not sure how I can test this:
https://github.com/stijnmoreels/arcus.eventgrid.proxy/blob/feature/add-yaml-release-docker-hub/build/dockerhub-release.yml

**Comment by tomkerkhove** [comment]
Just for your initial testing sake you can change the image name (https://github.com/stijnmoreels/arcus.eventgrid.proxy/blob/feature/add-yaml-release-docker-hub/build/dockerhub-release.yml#L7) to `arcusazure/arcus-event-grid-proxy-ignore` or one in your account. However, then I would comment the GitHub part.

Make sense to your are are you referring to something else?

*Nitpick - Docker Hub are two words so maybe rename to `docker-hub-release.yml`?*

**Comment by stijnmoreels** [comment]
Not sure if I understand this obscure error:
https://dev.azure.com/codit/Arcus/_build/results?buildId=39051&view=logs&j=2229703b-209a-5c70-43aa-3eacf674f12a

`Invalid reference format`
Any ideas?

**Comment by tomkerkhove** [comment]
Your image name is invalid:
![image](https://user-images.githubusercontent.com/4345663/68344360-d6740200-00bc-11ea-9248-9ab75ce7c851.png)

**Comment by stijnmoreels** [comment]
I think I need some help with this, I have to move the release to a YAML build but also move it to Docker tasks v2, which results in confused results since I don't know which values should be placed where. The 'Docker Repository' is for example a 'new' value in the v2 task that doesn't exist in v1. Same as image number which only existed in v1 but not in v2.

Maybe take this offline, of out of my hands.
